### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by franciscopassos** [vascoferreira25/arquivos_rtp_downloader#4]
.\artp-dl.exe https://arquivos.rtp.pt/conteudos/*censored*/

thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', D:\programming\Rust\arquivos_rtp_downloader\src/lib\video.rs:24:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', D:\programming\Rust\arquivos_rtp_downloader\src/lib\video_downloader.rs:49:28

Strange that there would be absolute paths in there that I don't have on my machine.

**Comment by vascoferreira25** [comment]
Hi,

That is in fact really curious. That is my usual path for my programming projects. I have to find why it happens as I don't have any static references to any path on the code base.

Thank you for finding it out. It must be something about the build step of the executable


On another note, unfortunately I think that the downloader isn't working, at least for most videos, as Arquivos RTP changed the on-demand streaming and now includes some sort of DRM protection. Even previously downloaded videos won't work anymore - not even with other software. I'm still figuring out if there is any way to make it work again

**Comment by ShaggyBro** [comment]
Looking for a way to download from RTP Arquivos currently. Any news?

**Comment by git99-debug** [comment]
Any news on this?

**Comment by claudiocoelho1977** [comment]
Hello,
Any news for download from RTP Arquivos - https://arquivos.rtp.pt/conteudos/independencia-ja-uma-historia-a-pretos-e-brancos-ep-1/
